### ISSUE TITLE
Problem with resolution with power management

### ISSUE THREAD

**Issue by macguru341** [daliansky/XiaoMi-Pro#107]
Hello
I have some strange problem:
After the laptop get into power saving mode (only turning the display off) and wake up i see the desktop on only quarter of the screen , I played with the energy saver option but it’s happing all the time .

**Comment by paajake** [comment]
Are you using HiDPI ? If you don't use the recommended resolution, you'll have issues, I do have this problem, to get it to full screen, click the apple logo and select sleep, but immediately the screen goes off, press spacebar to abort and  wake it up, this isn't a good  way out because, you'll have glittering screen on wake-up, the solution is a restart, or use the recommended resolution

**Comment by macguru341** [comment]
yes I'm using the HiDPI - what is the recommend resolution ?

**Comment by paajake** [comment]
Recommended resolution 1344 x 756

**Comment by macguru341** [comment]
Thanks - and when using this resolution, I will not have this problem?

**Comment by Menchen** [comment]
I got no problem with that so far
