### ISSUE TITLE
Proper platform id for GPU

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro#121]
I see you use 0x0591b platform id for Intel UHD620.
is there any reason for not using 0x0591b ?
Is there any advantage of using one over other ?

**Comment by stevezhengshiqi** [comment]
It is 0x59160000 actually... I wrote it in README. I believe I have briefly explained this question before. The reason to choose 5916 for UHD620 because it is recommended by main hackintosh forums. For example, in https://github.com/acidanthera/WhateverGreen/blob/master/WhateverGreen/kern_model.cpp, vit9696 wrote
`{ 0x5917, 0x5916, "Intel UHD Graphics 620" },`

, and in https://github.com/al3xtjames/Clover/blob/a918bc9ea7a53b8d369fa0bf7adf7c6954f81edf/rEFIt_UEFI/Platform/Settings.c, the author of Clover wrote
`case 0x5917: // "Intel UHD Graphics 620"`

, and also in https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-IGPU.dsl, Rehabman wrote
` // Kaby Lake/HD630
            0x5912, 0, Package()
            {
                "AAPL,ig-platform-id", Buffer() { 0x00, 0x00, 0x12, 0x59 },`

**Comment by stevezhengshiqi** [comment]
For more information, you can go to https://www.tonymacx86.com/forums/mojave-laptop-support.196/ and ask for professional help.
