### ISSUE TITLE
Is DTGP required on hotpatches?

### ISSUE THREAD

**Issue by sakoula** [daliansky/XiaoMi-Pro#133]
Hi,
I have noticed that many hotpatches include `External (DTGP, MethodObj)` such as SSDT-RMNE.dsl. Do they require the DTGP patch? If yes why is that. 

for example [SSDT-RMNE.dsl](https://github.com/RehabMan/OS-X-Null-Ethernet/blob/master/SSDT-RMNE.dsl) at RehabMan's site does not include the DTGP method/patch

Thanks!

**Comment by stevezhengshiqi** [comment]
Hi,
[DTGP method](https://clover-wiki.zetam.org/Fixing-DSDT#dsdt-mask_adddtgp_0001-bit-0) is not required in SSDTs necessarily. In [Rehabman's repo](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/tree/master/hotpatch), he uses
`
If (!Arg2) { Return (Buffer() { 0x03 } ) }
`
to replace DTGP method, which is good and simple.

The reason I use DTGP method is that many real MacBookPros use that. I want our devices behave more natively. Here's are two DSDT examples from MacBookPro14,1 and MacBookPro14,2 and you can see that almost every _DSM method followed by a DTGP method.(Please don't share, these files are just for hackintosh study!)
[MacBook Pro-14.1.acpi.zip](https://github.com/daliansky/XiaoMi-Pro/files/2718281/MacBook.Pro-14.1.acpi.zip)

**Comment by sakoula** [comment]
Hi, Thanks a lot for you super detailed reply. Actually I have a Xiaomi Mi Notebook Air 13.3'' (i5 6200U) and I am trying to learn while converting it to a hackintosh! The XiaoMi-Pro repository is an amazing knowledge treasure for me. Well done!!!

May I ask a couple of questions? 

1. How did you make the CPUFriendDataProvider for the Pro? Can you point me to some documentation/thread to start experimenting with (my battery life sucks). Does it make sense to install the Pro provider? I assume that it is a totally different architecture and will not be compatible.

2. I have big trouble with VoodooI2C. How can I tell the type of touchpad that I have? What tools are you using in Windows to see details of the devices? I cannot see the I2C devices under ioreg by no means.

Sorry for all these questions! 

Thanks! and Happy new year!

**Comment by stevezhengshiqi** [comment]
Happy new year! I am glad that you like my work.

1. I think you need to generate an unique CPUDataProvider because you have a different generation CPU. Full instruction is at:https://github.com/acidanthera/CPUFriend/blob/master/Instructions.md
I have explained my process before at 10th floor in [#22](https://github.com/daliansky/XiaoMi-Pro/issues/22), which may help you.
A easier way is to choose a compatible SMBIOS and check `plugin-type` in `config.plist`

2. For VoodooI2C, full instruction is at [here](https://voodooi2c.github.io/#GPIO%20Pinning/GPIO%20Pinning). You can go to `Device Manager` and find your trackpad.

**Comment by sakoula** [comment]
Thanks again!
