### ISSUE TITLE
Trackpad behavior on 10.14.3

### ISSUE THREAD

**Issue by nephthys** [daliansky/XiaoMi-Pro#156]
Hello,

I have the update of macOS 10.14.3 with the last release of this repository (v1.3.0), I read the note in the README and Tips for TrackPad.txt but the behavior of the touchpad / trackpad is strange.

When I try to select text with the trackpad, I can't select all the complete line, the selection stops when I haven't released the trackpad (so the selection should continue, normally). Even if I try to enlarge a window, it doesn't work normally and the window continues to resize a little while I released the trackpad.

I emptied the kext cache, disabled almost all the options in the settings (Scroll & zoom, etc.). I didn't have this problem on macOS 10.14.2 but I was using an older version of the repository...

Have you ever had this problem ?

Thanks.

**Comment by nephthys** [comment]
I have the problem on v1.2.9 too.

Before the update of macOS 10.14.3, I used a copy of this repository downloaded on December 9, 2018 (I don't know which version it is precisely, but it's not one of the last two versions). I just tested with it, and I don't have the problem.

**Comment by stevezhengshiqi** [comment]
Hi, I am sorry that I could not catch it when you said "When I try to select text with the trackpad, I can't select all the complete line, the selection stops when I haven't released the trackpad (so the selection should continue, normally)." Did you keep pressing down the trackpad and moving your fingers when you select the line? If you do, please check whether your system is damaged and replace you EFI folder completely because it seems nobody meet this problem before.

I personally suggest that you can turn on drag options in `SysPref-Accessibility-TouchPad`. 

BTW, if you need professional help of trackpad, it's better to go to [VoodooI2C's gitter room](https://gitter.im/alexandred/VoodooI2C) and describe your problems in detail.

**Comment by stevezhengshiqi** [comment]
Trackpad experience problems can't be solved. Try to connect the [author](https://github.com/alexandred/VoodooI2C) of VoodooI2C and report the issue.
