### ISSUE TITLE
Change VRAM size for Intel UHD Graphics

### ISSUE THREAD

**Issue by rlshukhov** [daliansky/XiaoMi-Pro#186]
Hello!

Are there any ways to reduce the amount of allocated RAM for integrated graphics?

**Comment by rlshukhov** [comment]
The system allocates 1536 MB (of 8 GB) for video memory, it seems to me too much.

**Comment by Menchen** [comment]
By ram you mean DVMT pre allocated? Or "VRAM"...

Reducing DVMT would kernel panic at boot.. so no.

And reducing "VRAM" is pointless... it shuold be dynamically allocated... It only use it when needed... and trust me 1.5G is not that much... considering dedicated graphic card have 2g...

**Comment by Menchen** [comment]
Btw in windows VRAM is 8g....

**Comment by stevezhengshiqi** [comment]
It's unrecommended to change the VRAM value since Apple gave most of their Intel Graphics products 1536MB VRAM. I think Apple do it for a reason and, it's danger to change the default value.

However, if you still want to try, you can open `config.plist` and add following lines:
```
<key>framebuffer-unifiedmem</key>
<data>AAAAQA==</data>
```
change the data value to the target VRAM you want.

**Comment by stevezhengshiqi** [comment]
Closing this issue because changing VRAM is not recommended.
