### ISSUE TITLE
No touchpad during install

### ISSUE THREAD

**Issue by Velkas** [daliansky/XiaoMi-Pro#27]
I've been trying for weeks now to get a stable install going on my Pro.

I create the macOS 10.13.4 USB installer from the full installer provided by Apple. Then I install clover using the installer in the repo. I rename the config file as mentioned in the installer. Then I boot up the laptop with the drive in it. It boots into the macOS installer but touchpad doesn't work and I have to plug in a mouse.

Once I get it installed I then use the same clover installer and install it with the options shown in the screenshots in the guide. Everything works except the touchpad still.

I just installed windows back onto the laptop and the touchpad works fine. No issues at all.

**Comment by stevezhengshiqi** [comment]
Thanks for reporting. It's a common problem of the installer. You need to run Kext Utility or some other software like Kext Wizard to clean the cache after installation. 

The reason behind is unknown, maybe the system cache need to be reloaded in order to let VoodooI2C works instead of native Apple I2C kexts.
