### ISSUE TITLE
"Win+P" doesn't work with the 5-16-2018 EFI

### ISSUE THREAD

**Issue by xream** [daliansky/XiaoMi-Pro#35]
"Win+P" does work in Windows.
"Win+P" does work with USB keyboards.

Any troubleshooting tip to see if I can get this issue fixed...

**Comment by stevezhengshiqi** [comment]
Please submit your troubleshooting to https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x . Keyboard kext problems are something beyond my ability.

**Comment by xream** [comment]
@stevezhengshiqi Thanks, man. Could you share your current complete EFI archive, please?

**Comment by stevezhengshiqi** [comment]
Sure, but I am not sure my EFI folder works well on your device. The reason is that I installed all my kexts in to /L/E, which is recommend by Rehabman. 
In https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/wiki/How-to-Install, it says
  
> starting with version 1.7.8, install the VoodooPS2Daemon

  sudo cp org.rehabman.voodoo.driver.Daemon.plist /Library/LaunchDaemons
  sudo cp VoodooPS2Daemon /usr/bin

If it works fine without VoodooPS2Daemon, please tell me. I will consider to update keyboard kext on github.
[EFI.zip](https://github.com/daliansky/XiaoMi-Pro/files/2142881/EFI.zip)

**Comment by xream** [comment]
Thanks for your reply. 

Noob here. To be clear, what I should do is:

1. Use your EFI archive

2. install VoodooPS2Controller.kext using Kext Utility.app

3. install the VoodooPS2Daemon

4. reboot

Am I right?

**Comment by stevezhengshiqi** [comment]
No, just delete your EFI folder and replace. If it doesn't work, i=you have to move all your kexts into /L/E, install VoodooPS2Daemon, and set InjectKext mode to "Detect".

**Comment by xream** [comment]
Good news, after replace the EFI and reboot, `cmd-p` works!

**Comment by stevezhengshiqi** [comment]
Thanks, I may update the keyboard kexts in the future. If somethings happened after sleep(like keyboard not work), please tell me.

**Comment by xream** [comment]
USB Wireless Adapter stops working after sleep. Is this related?

**Comment by stevezhengshiqi** [comment]
No.

**Comment by xream** [comment]
No wake up from sleep by keyboard(only the power button works) or trackpad.

**Comment by stevezhengshiqi** [comment]
It's normal.
