### ISSUE TITLE
About "Bluetooth Not Working" well mentioned in README

### ISSUE THREAD

**Issue by fanvinga** [daliansky/XiaoMi-Pro#50]
First of all, Thank you all for your fantastic work and make hackintosh on MiPro possible :-D.
However i am a little bit confusing about "Native Bluetooth is not working well".
i will be appreciated if you can explain it to me :)

**Comment by stevezhengshiqi** [comment]
In order to let the native Bluetooth work, people have to boot into Windows or Linux first, and then restart into macOS. In this way, the BT can connect to a majority of BT terminal. 

However, if people shut down the device(the power light on the right is off), and reopen macOS, the BT won't work. Also, BT will malfunction after long time sleep. 

Briefly, the reason is that our Intel BT is probably a RAMUSB device, while 

> original Apple Broadcom bluetooth devices are not RAMUSB devices, and thus do not have the same firmware mechanism. - [According to Rehabman](https://github.com/RehabMan/OS-X-BrcmPatchRAM/blob/master/README.md)

Currently, I haven't found anyone who is working on out Intel BT, and I am not capable of writing this kind of driver.

**Comment by fanvinga** [comment]
Thanks for your patient explain :-D
i have heard that in order to solve RAMUSB device firmware update problem , Rehabman created BCMPatchRam2.kext . Maybe it can help ?

**Comment by stevezhengshiqi** [comment]
No, it can't. It's not related to Intel BT.

**Comment by fanvinga** [comment]
OK.Thanks :-D
