### ISSUE TITLE
Update into Mojave

### ISSUE THREAD

**Issue by Raphencoder** [daliansky/XiaoMi-Pro#86]
Hey, thanks for all the good work !!

I have installed high sierra on my Hackintosh and I wanted to know if I can update to Mojave without any new issues.

Now everything works except wifi (I use dongle that works fine) and bluetooth. 

Thank you !

**Comment by stevezhengshiqi** [comment]
@Raphencoder Hi, if you are using 1.2.8 issue, then you can update to Mojave without new issues. Personally I suggest to create a new partition to experience Mojave for a few days. If it's OK, then update.

**Comment by sebmoris** [comment]
My every update executes in such a way that it overwrites the whole EFI folder which I download from the repository, but earlier to the notebook I have entered the mac data generated numbers during the first installation, because icloud later sees the next device with new serial numbers. So it's better to write them down somewhere. The data I have in the notebook is ROM number in RT variables, custom uuid is same as smuuid, system and board serial number. 
After overwriting the entire BOOT and CLOVER folder in the EFI folder, then entering my serial data, and selecting the same Mac model from the list, I have not yet done so that the system did not get up and had some problems with icloud.
Greetings.
