### ISSUE TITLE
HIDPI for Mi Pro Huge fonts

### ISSUE THREAD

**Issue by paajake** [daliansky/XiaoMi-Pro#89]
I upgraded successfully to Mojave my only issue is the new HIDPI, when I use the recommended resolution of 1344x756, the fonts are too big, the default of 1600x800 looks better but parts of the screen are cut off, help please... @orditeck or anyone

**Comment by stevezhengshiqi** [comment]
@paajake Hi, although 1344x756 hidpi looks big, it's the highest resolution that can be supported by Mojave on our device. If the resolution is set higher than 1344x756 hidpi, people will suffer from ugly glitter during booting and small screen during wake up.

**Comment by stevezhengshiqi** [comment]
@paajake Hi, I updated the hidpi display file and 1600x900(HiDPI) resolution should work. However, you may encounter glitter problem during booting and wake up as I said.

**Comment by orditeck** [comment]
Just curious, why would one use HiDPI? I tested it and it just made everything look bigger. That would be why? To get a bigger UI? I guess that's the hole point of scaling anyway haha so that must be a stupid question.

Just asking because for me the whole point of getting a FHD display was to use all the space. It'd make sense to use HiDPI with a UHD screen but with a FHD?

**Comment by paajake** [comment]
@orditeck well the initial installation of the hackingtosh came with a resolution that made things look tiny, the only way out was to drop the resolution which made things bigger and blurry, the HiDPI allowed you to obtain higher resolutions and no blurry display

**Comment by orditeck** [comment]
Thanks @paajake & @Menchen, it confirms what I thought. To each its own use case!
